services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.136.0
    container_name: otel-collector

    command:
      - "--config=/etc/otelcol-contrib/config.yaml"

    volumes:
      - ./infrastructure/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml

    ports:
      - "14318:4318"
      - "8889:8889"

    depends_on:
      - tempo
      - loki

  tempo:
    image: grafana/tempo:2.8.2

    container_name: tempo

    command:
      - "-config.file=/etc/tempo/tempo.yaml"

    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo/tempo.yaml

    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  loki:
    image: grafana/loki:3.5.5

    container_name: loki

    command:
      - "-config.file=/etc/loki/config.yaml"

    volumes:
      - ./infrastructure/loki/loki-config.yaml:/etc/loki/config.yaml

    ports:
      - "3100:3100"
  
  grafana:
    image: grafana/grafana:12.2.0

    container_name: grafana

    ports:
      - "3001:3000"

    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning

    depends_on:
      - tempo
  
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: observability-prometheus

    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9091:9090"

    depends_on:
      - otel-collector
